# Generated by Django 5.1.1 on 2024-09-26 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Spares',
            new_name='Spare',
        ),
    ]
