# Generated by Django 5.1.1 on 2024-09-26 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0003_car_spare_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spare',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magazine.car'),
        ),
    ]
