# Generated by Django 5.1.1 on 2024-09-27 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0006_alter_spare_car_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spare',
            name='price',
            field=models.PositiveIntegerField(verbose_name='цена'),
        ),
    ]
