# Generated by Django 5.1.1 on 2024-09-28 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0007_alter_spare_price'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.UniqueConstraint(fields=('order', 'spare'), name='unique_order_spare'),
        ),
    ]
