# Generated by Django 5.1.1 on 2024-09-28 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0008_orderitem_unique_order_spare'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='выполнен'),
        ),
    ]
