# Generated by Django 5.1.1 on 2024-09-28 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0009_order_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='count',
            field=models.PositiveIntegerField(verbose_name='количество'),
        ),
    ]
