# Generated by Django 5.1.1 on 2024-09-29 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0010_alter_orderitem_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_cart',
            field=models.BooleanField(default=True, verbose_name='корзина'),
        ),
    ]
