# Generated by Django 5.1.1 on 2024-10-07 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0011_order_is_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='spare',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='order_photos/'),
        ),
    ]
